package:
  name: pyemma
  version: !!str dev
source:
  path: ../..

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20

    - bhmm
    - joblib
    - matplotlib
    - mdtraj
    - nose # actually this should not be here...
    - mock
    - msmtools
    - numpy >=1.7
    - scipy
    - six

  run:
    - python
    - setuptools
    - bhmm
    - joblib
    - matplotlib
    - mdtraj
    - mock
    - msmtools
    - numpy >=1.7
    - scipy
    - six

test:
  requires:
    - nose
    - coverage
  imports:
    - pyemma

about:
  home: http://emma-project.org
  license: BSD 2-Clause License
  summary: "EMMA: Emma's Markov Model Algorithms"


