steps:
  - bash: |
      conda config --add channels conda-forge
      conda config --set always_yes true
      conda config --set quiet true
    displayName: Configure conda
  - bash: |
      conda clean --all
      conda install mamba
      mamba update --all
    displayName: Update conda
  - bash: |
      mamba install boa conda-build conda-verify pip
    displayName: 'Install dependencies'
    continueOnError: false
  - bash: |
      export PYTHONUNBUFFERED=1
      conda mambabuild devtools/conda-recipe
    displayName: 'Build and test'
    continueOnError: false
