package:
  name: pyemma-dev
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG + '+' +GIT_BUILD_STR}}
source:
  path: ../..

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20

    - bhmm >=0.6,<0.7
    - joblib >0.8.4
    - matplotlib
    - mdtraj >=1.7
    - mock
    - funcsigs
    - msmtools
    - thermotools >=0.2.0
    - nose
    - numpy x.x 
    - pyyaml
    - scipy
    - six
    - psutil >=3.1.1
    - decorator >=4.0.0

  run:
    - python
    - setuptools
    - bhmm >=0.6,<0.7
    - joblib >0.8.4
    - matplotlib
    - mdtraj >=1.7
    - mock
    - funcsigs
    - msmtools
    - thermotools >=0.2.0
    - numpy x.x
    - pyyaml
    - scipy
    - six
    - psutil >=3.1.1
    - decorator >=4.0.0

test:
  requires:
    - nose
    - coverage ==4
  imports:
    - pyemma

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: "EMMA: Emma's Markov Model Algorithms"


