package:
  name: pyemma-dev
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. 2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG[1:] + '+' + GIT_DESCRIBE_NUMBER + '.' + GIT_DESCRIBE_HASH}}

source:
  path: ../..
  # borked, but preferable, because it creates a "clean" working copy locally.
  #git_url: ../../

build:
  script_env:
   - CIRCLE_TEST_REPORTS
   - OMP_NUM_THREADS
   - PYEMMA_NJOBS
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
# workaround for bpo-24935, the compiler jinja2 template sets CC, but LDSHARED is not being set accordingly by distutils.sysconfig.
  script: LDSHARED="$CC -shared" python setup.py install --single-version-externally-managed --record record.txt #  [linux and py35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - intel-openmp # [osx]

  host:
    - cython
    - intel-openmp # [osx]
    - mdtraj
    - numpy
    - python
    - scipy
    - setuptools
    - pip
    - pybind11
    - deeptime

  run:
    - bhmm >=0.6.3
    - decorator >=4.0.0
    - h5py
    - intel-openmp # [osx]
    - matplotlib
    - mdtraj >=1.8
    - msmtools >=1.2
    - {{ pin_compatible('numpy') }}
    - pathos
    - psutil >3.1
    - python
    - pyyaml
    - scipy
    - setuptools
    - tqdm
    - deeptime

test:
  source_files:
    - conftest.py
    - setup.cfg
  files:
    - matplotlibrc
  requires:
    - pytest
    - pytest-cov
    - coverage
    - pytest-faulthandler 
    - pytest-xdist
    - scikit-learn
    # https://github.com/Frozenball/pytest-sugar/issues/124
    #- pytest-sugar

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: "EMMA: Emma's Markov Model Algorithms"
