
package:
  name: pyemma-doc
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: "0"

source:
  - path: ../../doc/
  # TODO: does not cure that this file can not be icnluded in docs. (relative path issue)
  - path: ../../pyemma/pyemma.cfg
    folder: pyemma

requirements:
  build:
    - pyemma-dev
    - make
    - mdshare
    - nglview
    - nbconvert
    - sphinx
    - ipython
    - ipywidgets
    - sphinx_rtd_theme
    - pip
    # TODO: pinnig mpl does not help to fix empty plots in 00 notebook
    - matplotlib <3

build:
  #noarch: generic
  script_env:
  # options for sphinx builder
    - SPHINXOPTS
  # options for notebook conversion (jupyter nbconvert)
    - nbflags
  # cfg dir
    - PYEMMA_CFG_DIR
